FROM registry.access.redhat.com/ubi8/dotnet-60-runtime:6.0 AS base
WORKDIR /opt/app-root/app
EXPOSE 80

ENV ASPNETCORE_ENVIRONMENT "OPENSHIFT"

COPY ../publish/ .
USER 1001
ENTRYPOINT ["dotnet", "DotNet.Podman.dll"]
