trigger:
- main

pool:
  name: Default

variables:
  project-name-dev: 'ado-openshift'
  project-name-uat: 'ado-openshift'
  image-name: 'wk-dotnet'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: BuildAndPushJob
    displayName: Build and Push Job
    steps:
    - script: pwd && ls && dotnet build "app/DotNet.Podman.csproj" -c Release -o podman/app/build
      displayName: 'dotnet build'

    - script: pwd && ls && dotnet publish "app/DotNet.Podman.csproj" -c Release -o podman/app/publish
      displayName: 'dotnet publish'

    - script: pwd && ls && echo $(Build.SourcesDirectory)
      displayName: 'debug'

    - script: pwd && ls podman/app/publish && podman build -t dotnet-counter-app:$(Build.BuildId) -f podman/app/Containerfile --build-arg BUILD_DIR=$(Build.SourcesDirectory) && podman images 
      displayName: 'podman build'
