apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml

images:
- name: dotnet-counter-app
  newName: image-registry.openshift-image-registry.svc:5000/ado-openshift/dotnet-counter-app
  newTag: "65"
