kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'azure-build-sa-img-puller'
  namespace: azure-build # pulling image from azure-build
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:azure-build-1:azure-build-sa'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'
