FROM registry.access.redhat.com/ubi8/dotnet-60:latest
ENV _BUILDAH_STARTED_IN_USERNS="" \
    BUILDAH_ISOLATION=chroot \
    STORAGE_DRIVER=vfs

USER root
COPY start.sh .
RUN dnf install git jq podman-docker -y && \
    curl $AZP_AGENT_PACKAGE_LATEST_URL --output vsts-agent-linux-x64.tar.gz && \
    tar zxvf vsts-agent-linux-x64.tar.gz && \
    rm vsts-agent-linux-x64.tar.gz && \
    chmod 755 *.sh && chown -R default:root . && \
    touch /etc/containers/nodocker && \
    usermod --add-subuids 100000-165535 default && \
    usermod --add-subgids 100000-165535 default && \
    setcap cap_setuid+eip /usr/bin/newuidmap && \
    setcap cap_setgid+eip /usr/bin/newgidmap && \
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && \
    mv /opt/app-root/src/kustomize /usr/local/bin/kustomize && chown -R default:root /usr/local/bin/kustomize
USER 1001
ENTRYPOINT ["./start.sh"]